/**
 * AgentFactory — CLI tool for scaffolding new agents.
 *
 * Usage:
 *   tsx src/agents/AgentFactory.ts create-agent <name> --description "..." --model "..." --skills "s1,s2"
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const AGENTS_DIR = path.resolve(__dirname);

export interface CreateAgentOptions {
  name: string;
  description: string;
  model: string;
  skills: string[];
  integrations?: Array<{ name: string; config: Record<string, unknown> }>;
}

/**
 * Validate an agent name for use as a directory/file name.
 */
function validateAgentName(name: string): boolean {
  return /^[A-Z][a-zA-Z0-9-]*$/.test(name);
}

/**
 * Scaffold a new agent directory with config, prompt, and skills subfolder.
 */
export function createAgent(options: CreateAgentOptions): string {
  const { name, description, model, skills, integrations = [] } = options;

  if (!validateAgentName(name)) {
    throw new Error(
      `Invalid agent name "${name}". Must start with uppercase letter, contain only alphanumeric characters and hyphens.`,
    );
  }

  const agentDir = path.join(AGENTS_DIR, name);

  if (fs.existsSync(agentDir)) {
    throw new Error(`Agent "${name}" already exists at ${agentDir}`);
  }

  // Create directories
  const skillsDir = path.join(agentDir, "skills");
  fs.mkdirSync(skillsDir, { recursive: true });

  // Create config.ts
  const configContent = `import { AgentRegistry, type AgentConfig } from "../AgentRegistry.js";

/**
 * ${name} — Agent configuration.
 * Auto-generated by AgentFactory.
 */

const config: AgentConfig = {
  name: "${name}",
  description: "${description}",
  model: "${model}",
  skills: [${skills.map((s) => `"${s}"`).join(", ")}],
  integrations: [${integrations
    .map(
      (i) => `\n    { name: "${i.name}", config: ${JSON.stringify(i.config)} }`,
    )
    .join(", ")}
  ],
  status: "idle",
};

AgentRegistry.register(config);
export default config;
`;

  fs.writeFileSync(path.join(agentDir, "config.ts"), configContent, "utf-8");

  // Create prompt.md
  const promptContent = `# ${name} — System Prompt

## Identity
You are ${name}, an agent within the J.A.R.V.I.S. system.

## Description
${description}

## Model
${model}

## Skills
${skills.length > 0 ? skills.map((s) => `- ${s}`).join("\n") : "_No skills assigned._"}

## Integrations
${integrations.length > 0 ? integrations.map((i) => `- ${i.name}`).join("\n") : "_No integrations configured._"}

## Instructions
<!-- Add agent-specific instructions here -->
`;

  fs.writeFileSync(path.join(agentDir, "prompt.md"), promptContent, "utf-8");

  // Create skills/ placeholder
  const skillsReadme = `# ${name} — Skills

Place skill implementation files in this directory.
Each file should import and self-register with SkillRegistry.
`;

  fs.writeFileSync(
    path.join(skillsDir, "README.md"),
    skillsReadme,
    "utf-8",
  );

  return agentDir;
}

/**
 * CLI entry point.
 */
function main(): void {
  const args = process.argv.slice(2);

  if (args[0] !== "create-agent" || args.includes("--help")) {
    console.log(`
AgentFactory — Scaffold a new J.A.R.V.I.S. agent.

Usage:
  tsx src/agents/AgentFactory.ts create-agent <name> [options]

Options:
  --description <text>   Agent description (required)
  --model <name>         Model identifier (default: "gpt-4")
  --skills <s1,s2,...>   Comma-separated skill names
  --help                 Show this help message

Example:
  tsx src/agents/AgentFactory.ts create-agent Researcher --description "Deep research specialist" --model "claude-3-opus" --skills "web-search,analysis"
`);
    process.exit(args.includes("--help") ? 0 : 1);
  }

  const name = args[1];
  const description =
    args[args.indexOf("--description") + 1] || "No description provided";
  const model =
    args[args.indexOf("--model") + 1] || "gpt-4";
  const skillsStr = args[args.indexOf("--skills") + 1] || "";
  const skills = skillsStr
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  try {
    const agentDir = createAgent({ name, description, model, skills });
    console.log(`✅ Agent "${name}" created at: ${agentDir}`);
    console.log(`   - ${agentDir}/config.ts`);
    console.log(`   - ${agentDir}/prompt.md`);
    console.log(`   - ${agentDir}/skills/`);
  } catch (err) {
    if (err instanceof Error) {
      console.error(`❌ Error: ${err.message}`);
    }
    process.exit(1);
  }
}

// Only run CLI when invoked directly
const isDirectRun = process.argv[1] &&
  (process.argv[1].endsWith("AgentFactory.ts") || process.argv[1].endsWith("AgentFactory.js"));
if (isDirectRun) {
  main();
}
